# Similarities between List and Numpy Array's

# Differences between List and Numpy Array's 


### 1.List contain element of different data types whereas Arrays contains elemments of similar data type.

In [2]:
List = [1,'Sai',4.0]
print(List)

[1, 'Sai', 4.0]


In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Type conversion takes place if stored different datatypes

In [4]:
arr1 =np.array ([1,'Sai',4.0])
print(arr1)


['1' 'Sai' '4.0']


### 2. Ways of perfoming operations

#### .Arrays provide much flexibility  while performing mathematical operations than lists

In [7]:
arr = np.array([5,20,25,40])
print(arr)
type (arr)

[ 5 20 25 40]


numpy.ndarray

In [6]:
arr / 5

array([1., 4., 5., 8.])

In [9]:
list = [5,20,25,40]
print(list)

[5, 20, 25, 40]


In [11]:
 list / 5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### 3. Installation

#### . To use numpy arrays we need to install and import numpy library. whereas list is built in and we no need to install anything and we can directly use it.

## Advantages of arrays over list 

#### .Numpy arrays consumes less Memory.

#### Numpy arrays are fast than lists. 