# Numpy 

#### NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python


## What is an array

#### An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## initially Lets import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [12]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
## check the shape of the array

arr.shape

(3, 5)

## Indexing 

In [9]:
## Accessing the array elements

arr = ([1,2,3,4,5])

In [10]:
arr

[1, 2, 3, 4, 5]

In [11]:
arr[3]

4

In [14]:
arr1 

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [16]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [17]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [21]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
arr1=np.arange(0,10).reshape(2,5)

In [23]:
arr2=np.arange(0,10).reshape(2,5)

In [24]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [25]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
## random distribution
np.random.rand(3,3)

array([[0.33127743, 0.4823067 , 0.49127224],
       [0.42732954, 0.21662   , 0.95180925],
       [0.58503232, 0.26850503, 0.48695065]])

In [27]:
arr_ex=np.random.rand(4,4)

In [28]:
arr_ex

array([[0.13685994, 0.86614537, 0.95309897, 0.68002053],
       [0.26617743, 0.25063996, 0.02989519, 0.19217496],
       [0.92183092, 0.32584802, 0.14777818, 0.0572164 ],
       [0.31527773, 0.69489647, 0.77978639, 0.53531489]])