# Numpy Array Dimensions

### 1.1-Dimensional Array

### 2.2-Dimensional Array 

### 3.3-Dimensional Array

In [1]:
#importing Numpy Library
import numpy as np

In [2]:
#creating a scalar array
s = np.array(6)
print(s)

6


In [3]:
#checking data type
print(s.dtype)

int32


In [4]:
#check the dimension
print(np.ndim(s))

0


### Creating one dimensional array

In [5]:
a = [1,2,3,4,5]
A =np.array(a)
print(A)

[1 2 3 4 5]


In [6]:
#checking data type
print(A.dtype)

int32


In [7]:
#check the dimension
print(np.ndim(A))

1


### Creating two dimensional array

In [8]:
b = [[1,2,3],[4,5,6],[7,8,9]]
B =np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#check the dimension
print(np.ndim(B))

2


### Creating three dimensional array

In [10]:
c = [[[1,2]],[[3,4]],[[4,5]],[[5,6]]]
C =np.array(c)
print(C)

[[[1 2]]

 [[3 4]]

 [[4 5]]

 [[5 6]]]


In [11]:
#check the dimension
print(np.ndim(B))

2


In [13]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3
