# View Vs Copy in Numpy

Note 

1.Changes made to view will affect to the original array , whereas changes made to copy will not affect original array. 

2.view is just view of original array & copy is like creating a new array.

In [1]:
#importing numpy package
import numpy as np

## Let's understand functionality of view ()

Note: View doesn't owns the data.

In [2]:
arr1 = np.array([10,20,30,40])
print (arr1)

[10 20 30 40]


In [4]:
arr2 = arr1.view()
arr2[1] = 100

In [5]:
print (arr2)

[ 10 100  30  40]


In [6]:
print (arr1)

[ 10 100  30  40]


## Let's understand the functionality of copy() 

In [7]:
arr1 = np.array([10,20,30,40])
print (arr1)

[10 20 30 40]


In [8]:
arr2 = arr1.copy()
arr2[1] = 100

In [9]:
print (arr2)

[ 10 100  30  40]


In [10]:
print (arr1)

[10 20 30 40]


# Hstack vs Vstack

Note:

1.Hstack is used to join two arrays Horizontally.

2.Vstack is used to join two arrays Vertically.

In [11]:
#importing numpy package
import numpy as np

## Performing Hstack 

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a:{}" .format(a))
print("Dimension of a: ", a.ndim)

print("b:{}" .format(b))
print("Dimension of b: ", b.ndim)

a:[1 2 3]
Dimension of a:  1
b:[4 5 6]
Dimension of b:  1


In [17]:
c = np.hstack((a,b))
print("c:{}" .format(c))
print("Dimension of c: ", c.ndim)

c:[1 2 3 4 5 6]
Dimension of c:  1


## Performing Vstack 

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a:{}" .format(a))
print("Dimension of a: ", a.ndim)

print("b:{}" .format(b))
print("Dimension of b: ", b.ndim)

a:[1 2 3]
Dimension of a:  1
b:[4 5 6]
Dimension of b:  1


In [19]:
c = np.vstack((a,b))
print("c:{}" .format(c))
print("Dimension of c: ", c.ndim)

c:[[1 2 3]
 [4 5 6]]
Dimension of c:  2


# Numpy Concatenation

In [20]:
#importing numpy package
import numpy as np

In [22]:
#Array A
a = [[1,2],[3,4]]
A = np.array(a)
print(A)
print(A.shape)

[[1 2]
 [3 4]]
(2, 2)


In [23]:
#Array B

b = [[7],[8]]
B = np.array(b)
print(B)
print(B.shape)

[[7]
 [8]]
(2, 1)


In [24]:
#Array C

c = [[9,10]]
C = np.array(c)
print(C)
print(C.shape)

[[ 9 10]]
(1, 2)


Note:

1.When axis = 0 , Both concatenate arrays should have same number of columns [like adding a new row]

2.When axis = 1 , Both concatenate arrays should have same number of rows [like adding a new column]

### Let's concatenate A & C

In [25]:
print(A.shape)

(2, 2)


In [26]:
print(C.shape)

(1, 2)


In [27]:
#here we have same no.of columns
D = np.concatenate((A,C), axis=0)
print(D)
print(D.shape)

[[ 1  2]
 [ 3  4]
 [ 9 10]]
(3, 2)


### Let's concatenate A & B

In [28]:
print(A.shape)

(2, 2)


In [29]:
print(B.shape)

(2, 1)


In [30]:
#here we have same no.of rows
E= np.concatenate((A,B), axis=1)
print(E)
print(E.shape)

[[1 2 7]
 [3 4 8]]
(2, 3)


# Insert, Append & Delete Numpy Array

In [31]:
#importing numpy package
import numpy as np

### Appending

In [33]:
a = [1,2,3,4]
A = np.array(a)
print(A)

[1 2 3 4]


Let's append 45 to array 

In [34]:
np.append(A,45)

array([ 1,  2,  3,  4, 45])

Let's append multiple values to array

In [35]:
#while appending multiple values make sure that you pass through lists only
np.append(A,[100,150,80])

array([  1,   2,   3,   4, 100, 150,  80])

Note: np.append() doesn't update original array , if you want the changes include make sure you create a new varaible.

In [36]:
print(A)

[1 2 3 4]


In [37]:
B = np.append(A, 45)
print(B)

[ 1  2  3  4 45]


In [39]:
B = np.append(B,[100,150,80])
print(B)           #here changes are permanently done.

[  1   2   3   4  45 100 150  80 100 150  80]


### Insertion in 2D Array 

In [40]:
b = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(b)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Adding new row to matrix

.Need to mention axis = 0 for appending to the rows

In [41]:
arr3 = np.append(arr2,[[10,11,12]], axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Adding new column to matrix

.Need to mention axis = 1 for appending to the column values.

In [42]:
arr4 = np.append(arr2,[[10],[11],[12]], axis=1)
print(arr4)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


# Inserting elements into Array

One- dimensional 

General format : (Array,index,value)

In [43]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [50]:
#insering -100 at first position of numpy array
np.insert(A,1,-100)

array([   1, -100,    2,    3,    4])

Two - dimensional 

General format : (Array,index_to_add,values,axis)

In [46]:
b = [[1,2,3],[4,5,6],[7,8,9]]
B= np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Inserting new row at first position of numpy matrix

In [47]:
np.insert(B,1,[120,40,25],axis=0)

array([[  1,   2,   3],
       [120,  40,  25],
       [  4,   5,   6],
       [  7,   8,   9]])

# Deletion

One- dimensional Array

General format : (Array,index_to_delete)

In [48]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [49]:
#let's delete the element which is present at 2nd index
np.delete(A,2)

array([1, 2, 4])

Two - dimensional Array

General format : (Array,which_row_column_delete,axis)

axis=0 for rows

axis=1 for columns

In [51]:
b = [[1,2,3],[4,5,6],[7,8,9]]
B= np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#let's delete 2nd row in matrix B
np.delete(B,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [55]:
#let's delete 2nd column in matrix B
np.delete(B,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

# Searching Arrays

## np.where()

In [56]:
#importing numpy package
import numpy as np

General Format:

np.where(condition,array,replcement)

1.condition we wnat to check

2.put the values in the arrays as it is, if cindition is met.

3.replacement happens when condition fails

In [57]:
a = [0,1,2,3,4,5,6,7,8,9]
A = np.array(a)
print(A)

[0 1 2 3 4 5 6 7 8 9]


.Replace all odd numbers with -1 

In [62]:
new_A = np.where(A%2==0 ,A ,-1)

In [59]:
print(new_A)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Task 2

In [61]:
b = [-1,7,3,-2,12,14,100,-3]
B = np.array(b)
print(B)

[ -1   7   3  -2  12  14 100  -3]


Let's replace all values less than 0 with 45

In [63]:
new_B = np.where(B>0 ,B ,45)
print(new_B)

[ 45   7   3  45  12  14 100  45]
